# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XSV24iMTQ5KZb1UVdJpoRVEbrdcy8cE_
"""

import json
import boto3
import snscrape.modules.twitter as sntwitter
import schedule
import datetime
import tweepy

# collecting trends
def trendscrape():
    ckey = "LplZ9PqomKaEnSrTii429l8ci"
    csecret = "3lqZkRwurnXoPCdOUtzYhFMolRRnwt4zIE9ElDY2d7HLtwK5ZE"
    atoken = "1505128383004672000-vXQ6CqmtzLoZRNElMlQHZ98n0vegnj"
    asecret = "p8R1UhR5bWygQTvmpd8Ie76yyUPsD8jeCXihEFyrIben9"
    auth = tweepy.OAuthHandler(ckey, csecret)
    auth.set_access_token(atoken, asecret)
    api = tweepy.API(auth)
    # WOEID of London
    woeid = 44418
    # fetching the trends
    keywords = []
    trends = api.get_place_trends(id=woeid, exclude="hashtags")
    for value in trends:
        for trend in value['trends']:
            keywords.append(trend['name'])
    return keywords

trend = trendscrape()

def lambda_handler(event, context):
     
    bucket = 'dbwpteam1' #당신의 버킷 이름
    file_name = str(datetime.datetime.now())[:-7]
    file = []
    for i, j in enumerate(trend):
        file.append(j)
        
    result = upload_file_s3(bucket, file_name + '.json', file)

    if result:
        return {
            'statusCode': 200,
            'body': json.dumps("upload success")
        }
    else:
        return {
            'statusCode': 400,
            'body': json.dumps("upload fail")
        }


def upload_file_s3(bucket, file_name, file):
    encode_file = bytes(json.dumps(file).encode('UTF-8'))
    s3 = boto3.client('s3')
    try:
        s3.put_object(Bucket=bucket, Key=file_name, Body=encode_file)
        return True
    except:
        return False
 
    return {
        'statusCode': 200,
        # 'body': json.dumps(trend)
        'body': json.dumps("Hello from LAMDA!")

    }